---
abstract: 'Brazilian phone numbers'
author:
  - 'André Walker <andre@andrewalker.net>'
build_requires:
  Test::Fatal: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Number-Phone-BR
provides:
  Number::Phone::BR:
    file: lib/Number/Phone/BR.pm
    version: '0.001'
  Number::Phone::BR::Areas:
    file: lib/Number/Phone/BR/Areas.pm
    version: '0.001'
requires:
  Moo: '0'
  Number::Phone: '0'
resources:
  bugtracker: https://github.com/andrewalker/p5-number-phone-br/issues
  repository: git://github.com/andrewalker/p5-number-phone-br.git
version: '0.001'
